### ISSUE TITLE
/CEI  /cei not working and The interface that appears for me is not visible to my players.

### ISSUE THREAD

**Issue by Mete2345** [StanleyDudek/CobaltEssentialsInterface#22]
![image](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/130308666/bf2f03f2-2266-4f24-ad1e-e09f6aa8937d)

**Comment by Mete2345** [comment]
![image](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/130308666/64f3a0cb-a5f3-46ab-8fca-8dbcd58cca7f)
![image](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/130308666/cc845ec1-4c6e-4ab2-abf9-4ecc0b4866bd)

**Comment by Mete2345** [comment]
CobaltEssentialsInterface : 1.7.91
CobaltEssentials : 1.7.6
Launcher : 2.0.82

**Comment by Mete2345** [comment]
![image](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/130308666/73be16f5-9957-41a1-8a32-684e2781ed71)

**Comment by Mete2345** [comment]
![image](https://github.com/StanleyDudek/CobaltEssentialsInterface/assets/130308666/7573b775-af28-4641-9a89-edbff9a90a75)

**Comment by git-mdgk** [comment]
Hello. Not sure why but /CEI not working. However, the CEI itself works. In order to show the menu interface for players go to CobaltDB -> playersDB folder, and edit players db files manually. Change "showCEI" to "true".

Or simply reset all database by removing all the files in playersDB. But make sure the Default CEI state is 'Showing' in Config tab. In this way all new players will have UI showing form the start.

**Comment by StanleyDudek** [comment]
As @git-mdgk said.

Please make sure CE and CEI are up to date, clear your DB, and follow the instructions in the [Readme](https://github.com/StanleyDudek/CobaltEssentialsInterface#readme)  

Open a new issue if problems persist.
